### PR TITLE
Allow using LTO

### PR DESCRIPTION
**Pull request by shivjm**
A temporary PR to try to make LTO work.

### CODE REVIEW

**Comment by shivjm** [comment]
Enabling LTO no longer immediately fails, but I see an inexplicable error from a transitive dependency:
```
rust_indexmap> unpacking sources
rust_indexmap> unpacking source archive /nix/store/5spmgn770xg2ljzgizdb7sfqpq8rjcsc-crate-indexmap-1.9.1.tar.gz
rust_indexmap> source root is indexmap-1.9.1
rust_indexmap> patching sources
rust_indexmap> configuring
rust_indexmap> building
rust_indexmap> Building build script: RUSTC 'build.rs' '--out-dir=/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin' '--crate-name=build_script_build' '--crate-type=bin' '--emit=link' '--color=always' '-Copt-level=0' '-Cembed-bitcode=no' '-Ccodegen-units=256' '--cap-lints=allow' '-Cmetadata=932724d44300e6de' '--edition=2021' '--cfg=feature="std"' '--extern=autocfg=/nix/store/qfnfiz5k23by80cg0j54i9idrj2jkl7f-rust_autocfg-1.1.0/lib/libautocfg-aad14ca23028c2cd.rlib' '-Ldependency=/build/tmp.N4LMy7YcB1'
rust_indexmap> error: linking with `cc` failed: exit status: 1
rust_indexmap>   |
rust_indexmap>   = note: "cc" "-m64" "/build/rustcSwqv3f/symbols.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.0.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.1.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.10.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.11.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.12.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.13.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.14.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.15.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.16.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.17.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.18.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.19.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.2.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.20.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.21.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.22.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.23.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.24.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.25.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.3.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.4.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.5.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.6.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.7.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.8.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.9.rcgu.o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.4iwvxia3zk7ow4e9.rcgu.o" "-Wl,--as-needed" "-L" "/build/tmp.N4LMy7YcB1" "-L" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/nix/store/qfnfiz5k23by80cg0j54i9idrj2jkl7f-rust_autocfg-1.1.0/lib/libautocfg-aad14ca23028c2cd.rlib" "-Wl,--start-group" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-43d49bfa007d9a20.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-3471383b1ce7e4b4.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-742926817ac5e7e5.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-240180d24a67821e.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-f4f04b6af5db1533.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-5e4b8b295e505b0a.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-ceac422729e88bc0.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-ccb74e221f5785c3.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-a2c508ce55c48d55.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-e372a7b96ab850a7.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-8640a6ef4c16fedd.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-932eae132a9d2dfd.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-af9b8fc59134a0f3.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-e0f7a6c19844cccb.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-e841830efb136523.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-818db47d8cb35a6b.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-46c6670f73127d69.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-c6b6edc5d71665ef.rlib" "-Wl,--end-group" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-b27d69bd96112472.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
rust_indexmap>   = note: /nix/store/frriydwnf7v3dpayy5a6ki00qsp95iiy-binutils-2.38/bin/ld: /nix/store/fi1wbm0awfw6pflz72qrzacpl15s7bz0-rust_indexmap-1.9.1-build/bin/build_script_build.build_script_build.4450578b-cgu.17.rcgu.o: in function `build_script_build::main':
rust_indexmap>           build_script_build.4450578b-cgu.17:(.text._ZN18build_script_build4main17h497ead93971db982E+0x33): undefined reference to `autocfg::new'
rust_indexmap>           /nix/store/frriydwnf7v3dpayy5a6ki00qsp95iiy-binutils-2.38/bin/ld: build_script_build.4450578b-cgu.17:(.text._ZN18build_script_build4main17h497ead93971db982E+0x4a): undefined reference to `autocfg::emit'
rust_indexmap>           /nix/store/frriydwnf7v3dpayy5a6ki00qsp95iiy-binutils-2.38/bin/ld: build_script_build.4450578b-cgu.17:(.text._ZN18build_script_build4main17h497ead93971db982E+0x8d): undefined reference to `autocfg::AutoCfg::emit_sysroot_crate'
rust_indexmap>           /nix/store/frriydwnf7v3dpayy5a6ki00qsp95iiy-binutils-2.38/bin/ld: build_script_build.4450578b-cgu.17:(.text._ZN18build_script_build4main17h497ead93971db982E+0xf5): undefined reference to `autocfg::rerun_path'
rust_indexmap>           collect2: error: ld returned 1 exit status
rust_indexmap>
rust_indexmap>   = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
rust_indexmap>   = note: use the `-l` flag to specify native libraries to link
rust_indexmap>   = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
rust_indexmap> error: aborting due to previous error
```
This is despite autocfg explicitly being in the dependency tree.

**Comment by shivjm** [comment]
At first glance, this would appear to be an issue with autocfg. With another, non–autocfg-using application, I get a different error:
```
rust_thiserror-impl> unpacking sources
rust_thiserror-impl> unpacking source archive /nix/store/kk3qpy0f34gshvn86pvkxfn5msp62sm8-crate-thiserror-impl-1.0.20.tar.gz
rust_thiserror-impl> source root is thiserror-impl-1.0.20
rust_thiserror-impl> setting SOURCE_DATE_EPOCH to timestamp 1592263341 of file thiserror-impl-1.0.20/Cargo.toml
rust_thiserror-impl> patching sources
rust_thiserror-impl> configuring
rust_thiserror-impl> building
rust_thiserror-impl> Building lib: RUSTC 'src/lib.rs' '--out-dir=/nix/store/bmhcy4a95dja9grx7s21kv06yb7b0lhz-rust_thiserror-impl-1.0.20/lib' '--crate-name=thiserror_impl' '--crate-type=proc-macro' '--emit=metadata,link' '-Cextra-filename=-fac442cbeb8eeedb' '--color=always' '-Copt-level=3' '-Cdebuginfo=0' '-Cdebug-assertions=no' '-Coverflow-checks=no' '-Clto=yes' '-Clinker-plugin-lto' '-Cpanic=abort' '-Ccodegen-units=1' '--cap-lints=allow' '-Cmetadata=fac442cbeb8eeedb' '--edition=2018' '--extern=proc_macro' '--extern=proc_macro2=/nix/store/158b5j90mp8mf8rcgs63h1297zjz1z8v-rust_proc-macro2-1.0.9/lib/libproc_macro2-315327f3c5943d51.rlib' '--extern=quote=/nix/store/p1qqrzlskjfbjlmybcf3b74c8iw9n6am-rust_quote-1.0.2/lib/libquote-19c0e08268c14d2f.rlib' '--extern=syn=/nix/store/cpyji9cgfksaz61238zyggcvvchww47l-rust_syn-1.0.16/lib/libsyn-6c45a3b18d221d9d.rlib' '-Ldependency=/nix/store/5q8wgi5qs7m015bybn1s984fg08qrj7v-rust_thiserror-impl-1.0.20-dev/rust-support/deps-closure'
rust_thiserror-impl> error: lto can only be run for executables, cdylibs and static library outputs
rust_thiserror-impl> error: aborting due to previous error
error: builder for '/nix/store/4xhii2d9ra9r7wqwp7m84nm7kldv9hqd-rust_thiserror-impl-1.0.20.drv' failed with exit code 1
```

**Comment by shivjm** [comment]
After implementing that, I’m running into the same sort of error as before with a different crate in a much simpler application:
```
rust_proc-macro-error-attr> unpacking sources
rust_proc-macro-error-attr> unpacking source archive /nix/store/ylag5clc7v9sf2817yma575hdrcvp54p-crate-proc-macro-error-attr-1.0.2.tar.gz
rust_proc-macro-error-attr> source root is proc-macro-error-attr-1.0.2
rust_proc-macro-error-attr> setting SOURCE_DATE_EPOCH to timestamp 1586443385 of file proc-macro-error-attr-1.0.2/.cargo_vcs_info.json
rust_proc-macro-error-attr> patching sources
rust_proc-macro-error-attr> configuring
rust_proc-macro-error-attr> building
rust_proc-macro-error-attr> Building build script: RUSTC 'build.rs' '--out-dir=/nix/store/f5nivkj28z3jbxx184i6hrhd4nqfxri4-rust_proc-macro-error-attr-1.0.2-build/bin' '--crate-name=build_script_build' '--crate-type=bin' '--emit=link' '--color=always' '-Copt-level=0' '-Ccodegen-units=256' '--cap-lints=allow' '-Cmetadata=6633d5332e7f9039' '--edition=2018' '--extern=version_check=/nix/store/73j2lgzjwipw3lalcc6hpygwgkph8rkz-rust_version_check-0.9.1/lib/libversion_check-4e6fd03c1436353d.rlib' '-Ldependency=/build/tmp.kUchWfep1F'
rust_proc-macro-error-attr> error: linking with `cc` failed: exit status: 1
rust_proc-macro-error-attr>   |
rust_proc-macro-error-attr>   = note: "cc" "-m64" "/build/rustcXAQY3R/symbols.o" "/nix/store/f5nivkj28z3jbxx184i6hrhd4nqfxri4-rust_proc-macro-error-attr-1.0.2-build/bin/build_script_build.build_script_build.c72f4903-cgu.0.rcgu.o" "/nix/store/f5nivkj28z3jbxx184i6hrhd4nqfxri4-rust_proc-macro-error-attr-1.0.2-build/bin/build_script_build.build_script_build.c72f4903-cgu.1.rcgu.o" "/nix/store/f5nivkj28z3jbxx184i6hrhd4nqfxri4-rust_proc-macro-error-attr-1.0.2-build/bin/build_script_build.build_script_build.c72f4903-cgu.2.rcgu.o" "/nix/store/f5nivkj28z3jbxx184i6hrhd4nqfxri4-rust_proc-macro-error-attr-1.0.2-build/bin/build_script_build.build_script_build.c72f4903-cgu.3.rcgu.o" "/nix/store/f5nivkj28z3jbxx184i6hrhd4nqfxri4-rust_proc-macro-error-attr-1.0.2-build/bin/build_script_build.build_script_build.c72f4903-cgu.4.rcgu.o" "/nix/store/f5nivkj28z3jbxx184i6hrhd4nqfxri4-rust_proc-macro-error-attr-1.0.2-build/bin/build_script_build.build_script_build.c72f4903-cgu.5.rcgu.o" "/nix/store/f5nivkj28z3jbxx184i6hrhd4nqfxri4-rust_proc-macro-error-attr-1.0.2-build/bin/build_script_build.build_script_build.c72f4903-cgu.6.rcgu.o" "/nix/store/f5nivkj28z3jbxx184i6hrhd4nqfxri4-rust_proc-macro-error-attr-1.0.2-build/bin/build_script_build.build_script_build.c72f4903-cgu.7.rcgu.o" "/nix/store/f5nivkj28z3jbxx184i6hrhd4nqfxri4-rust_proc-macro-error-attr-1.0.2-build/bin/build_script_build.build_script_build.c72f4903-cgu.8.rcgu.o" "/nix/store/f5nivkj28z3jbxx184i6hrhd4nqfxri4-rust_proc-macro-error-attr-1.0.2-build/bin/build_script_build.34wrfq8senxdu7r3.rcgu.o" "-Wl,--as-needed" "-L" "/build/tmp.kUchWfep1F" "-L" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/nix/store/73j2lgzjwipw3lalcc6hpygwgkph8rkz-rust_version_check-0.9.1/lib/libversion_check-4e6fd03c1436353d.rlib" "-Wl,--start-group" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-43d49bfa007d9a20.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-3471383b1ce7e4b4.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-742926817ac5e7e5.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-240180d24a67821e.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-f4f04b6af5db1533.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-5e4b8b295e505b0a.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-ceac422729e88bc0.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-ccb74e221f5785c3.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-a2c508ce55c48d55.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-e372a7b96ab850a7.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-8640a6ef4c16fedd.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-932eae132a9d2dfd.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-af9b8fc59134a0f3.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-e0f7a6c19844cccb.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-e841830efb136523.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-818db47d8cb35a6b.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-46c6670f73127d69.rlib" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-c6b6edc5d71665ef.rlib" "-Wl,--end-group" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-b27d69bd96112472.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/nix/store/n7m9l6djxf3xcdc2dk9scc6rbpw825p9-rustc-1.63.0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/nix/store/f5nivkj28z3jbxx184i6hrhd4nqfxri4-rust_proc-macro-error-attr-1.0.2-build/bin/build_script_build" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
rust_proc-macro-error-attr>   = note: /nix/store/frriydwnf7v3dpayy5a6ki00qsp95iiy-binutils-2.38/bin/ld: /nix/store/f5nivkj28z3jbxx184i6hrhd4nqfxri4-rust_proc-macro-error-attr-1.0.2-build/bin/build_script_build.build_script_build.c72f4903-cgu.0.rcgu.o: in function `build_script_build::main':
rust_proc-macro-error-attr>           build_script_build.c72f4903-cgu.0:(.text._ZN18build_script_build4main17h1eb743e16b70d66bE+0x12): undefined reference to `version_check::is_max_version'
rust_proc-macro-error-attr>           collect2: error: ld returned 1 exit status
rust_proc-macro-error-attr>
rust_proc-macro-error-attr>   = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
rust_proc-macro-error-attr>   = note: use the `-l` flag to specify native libraries to link
rust_proc-macro-error-attr>   = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
rust_proc-macro-error-attr> error: aborting due to previous error
```
I think there’s some sort of incompatibility between LTO and how nocargo does things.

**Comment by oxalica** [comment]
AFAIK, fat LTO stores LLVM IR in object files and do some work with them at link time. Maybe `lld` is required in that case.
Currently we use the default C linker.

**Comment by shivjm** [comment]
I (sort of) see. Thanks for the idea. I tried switching the linker but [rust-lld is under a different path](https://stackoverflow.com/a/55809900/8492116), so I get:
```
rust_anyhow> error: linker `rust-lld` not found
rust_anyhow>   |
rust_anyhow>   = note: No such file or directory (os error 2)
rust_anyhow> error: aborting due to previous error
```
Since it turns out allowing LTO isn’t just a matter of flipping a switch, I’ll try working through the pills and understanding Nix better before returning to the attempt.

**Comment by oxalica** [comment]
The original issue is fixed in 69dc641ff910f2350480db76d619d2efad318d92 now.
`lto=thin` and `lto=fat` seem to work without linker change.
Still thanks for the work.

**Pull request closed without merging**
